name: Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }

permissions:
  contents: write

concurrency:
  group: metrics
  cancel-in-progress: true

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics (left)
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-left.svg
          base: header, activity, community, repositories, metadata

          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons

      - name: Metrics (right)
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-right.svg
          base: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_repositories: yes
          plugin_repositories_pinned: 4
